<?php
$v_params = $this->getParams();
$o_roteiro = $v_params['o_roteiro'];
//$o_praticadidatica = $v_params['o_praticadidatica'];
$v_praticasdidaticas = $v_params['v_praticasdidaticas'];
$tempratica=0;

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>
		Práticas Didáticas - Listar Práticas Didáticas
	</title>
	<link rel="stylesheet" type="text/css" href="template/css/default.css" />
</head>
<body>
 <?php 	
include("top.php");
include("menu.php")
?>

<div class="agile_info">
			<div class="w3_info">
				<h2>Roteiro</h2><br>
				    <div class="left margin">
						<label>Título</label><br>
						<div class="conteudoTexto">
							<?php echo $o_roteiro->getTituloRoteiro()?> <br>
						</div>
					</div>
					
					<div class="rightTop">
						<label>Visibilidade</label><br>
						<div class="conteudoTexto">
							<?php if ($o_roteiro->getIdVisibilidade()==1)
							         echo "Roteiro Privado";							         
							     else
							         echo "Roteiro Público";
							?><br>
						</div>
					</div>
				
					<div class="left margin">
						<br><label>Objetivos Específicos</label><br>
						<div class="conteudoTexto">
							<?php echo $o_roteiro->getObjEspecificoRoteiro()?> <br><br>
						</div>
					</div>						
			
					<div class="left margin">
						<label>Conteúdo Básico</label><br>
						<div class="conteudoTexto">
							<?php echo $o_roteiro->getConteudoBasicoRoteiro()?>
						</div>
					</div>
			</div>
</div>

<div class="agile_info">
				<div class="w3_info">
					<h2>Prática Didática</h2><br>
					<?php
                	foreach($v_praticasdidaticas AS $o_praticadidatica)
                	{ $tempratica = 1;
                    ?>
                    	<div class="left margin">
							<label>Motivação</label><br>
							<div class="conteudoTexto">
								<?php echo $o_praticadidatica->getMotivacaoPratica()?> <br>
							</div>
						</div>
						
						<div class="left margin">
							<label>Desenvolvimento</label><br><br>
							<a href='?controle=Atividade&acao=listarAtividades&in_idroteiro=<?php echo $o_roteiro->getIdRoteiro()?>&in_idpraticadidatica=<?php echo $o_praticadidatica->getIdPraticaDidatica()?>' class="bt_green" >Visualizar Atividades</a>
						</div>				
			
						<div class="left margin">
							<br><label>Avaliação</label><br>
								<div class="conteudoTexto">
									<?php echo $o_praticadidatica->getAvaliacaoPratica()?> 
								</div>
						</div>	
									
						<div class="left margin">
							<br><br><label>Conclusão</label><br>
								<div class="conteudoTexto">
								<?php echo $o_praticadidatica->getConclusaoPratica()?>
							</div>
						</div>
						
							<div class="left margin">
							<label>Ações</label><br><br>
								<a href='?controle=Roteiro&acao=listarRoteiro' class='bt_yellow'>Voltar</a>
								<a href='?controle=PraticaDidatica&acao=manterPraticaDidatica&in_idroteiro=<?php echo $o_roteiro->getIdRoteiro()?>&in_idpraticadidatica=<?php echo $o_praticadidatica->getIdPraticaDidatica()?>' class='bt_blue'>Editar Prática Didática</a>
								<a href='?controle=PraticaDidatica&acao=apagarPraticaDidatica&in_idroteiro=<?php echo $o_roteiro->getIdRoteiro()?>&in_idpraticadidatica=<?php echo $o_praticadidatica->getIdPraticaDidatica()?>' class='bt_red'>Apagar Prática Didática</a>
						</div>
						
				
			<?php
        	}?>
						
				</div>
		</div>

</body>
</html>