<?php

$v_params = $this->getParams();
$v_areasatuacao = $v_params['v_areasatuacao'];
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>
		Pratica Didatica | Listar Area de Atuação
	</title>
	<link rel="stylesheet" type="text/css" href="template/css/default.css" />
</head>
<body>
 <?php 	
	/*echo '<pre>';
var_dump($_REQUEST);
echo '</pre>';*/
include("top.php");
include("menu.php")
?>
	<div align="center">
		<table class='table_list' width="40%">
			<tr>
				<th>
					Descrição da Área de Atuação
				</th>
				<th colspan="2">
					Ações
				</th>
			</tr>
			<?php
			
			foreach($v_areasatuacao AS $o_areaatuacao)
			{ 
				?>
				<tr>
					<td>
						<div class="green"><?php echo $o_areaatuacao->getDescricaoAreaAtuacao()?></div>
					</td>
					<td align="center">
						<a href='?controle=AreaAtuacao&acao=manterAreaAtuacao&in_idareaatuacao=<?php echo $o_areaatuacao->getIdAreaAtuacao()?>' class='bt_blue'>Editar</a>
					</td>
					<td align="center">
						<a href='?controle=AreaAtuacao&acao=apagarAreaAtuacao&in_idareaatuacao=<?php echo $o_areaatuacao->getIdAreaAtuacao()?>' class='bt_red'>Apagar</a>
					</td>
				</tr>
				<?php
			}
			?>
		</table>
		<br />
			<a href="?controle=AreaAtuacao&acao=manterAreaAtuacao" class="bt_green">Nova Área de Atuação</a>
	</div>
</body>
</html>