<?php
$v_params = $this->getParams();
$o_roteiro = $v_params['o_roteiro'];
$o_praticadidatica = $v_params['o_praticadidatica'];
$v_atividades = $v_params['v_atividades'];
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<!--  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">-->

	<title>
		Práticas Didáticas - Listar Atividades
	</title>
	<link rel="stylesheet" type="text/css" href="template/css/default.css" />
</head>
<body>
 <?php 	
include("top.php");
include("menu.php")
?>
<div class="agile_info">
			<div class="w3_info">
				<h2>Roteiro</h2><br>
				    <div class="left margin">
						<label>Título</label><br>
						<div class="conteudoTexto">
							<?php echo $o_roteiro->getTituloRoteiro()?> <br>
						</div>
					</div>
					
					<div class="rightTop">
						<label>Visibilidade</label><br>
						<div class="conteudoTexto">
							<?php if ($o_roteiro->getIdVisibilidade()==1)
							         echo "Roteiro Privado";							         
							     else
							         echo "Roteiro Público";
							?><br>
						</div>
					</div>
				
					<div class="left margin">
						<br><label>Objetivos Específicos</label><br>
						<div class="conteudoTexto">
							<?php echo $o_roteiro->getObjEspecificoRoteiro()?> <br><br>
						</div>
					</div>						
			
					<div class="left margin">
						<label>Conteúdo Básico</label><br>
						<div class="conteudoTexto">
							<?php echo $o_roteiro->getConteudoBasicoRoteiro()?>
						</div>
					</div>
			</div>
</div>

<div class="agile_info">
				<div class="w3_info">
					<h2>Prática Didática</h2><br>
					
                    	<div class="left margin">
							<label>Motivação</label><br>
							<div class="conteudoTexto">
								<?php echo $o_praticadidatica->getMotivacaoPratica()?> <br>
							</div>
						</div>
						
						<div class="left margin">
							<label>Desenvolvimento</label><br><br>
							<?php
					        foreach($v_atividades AS $o_atividade)
    					    {   
					        ?>
			                    	<div class="left margin">
										<label>Descrição da Atividade</label><br>
										<div class="conteudoTexto">
											<?php echo $o_atividade->getDescricaoAtividade()?> <br>
										</div>
									</div>
									
								<div class="borderAtividade">
									<div class="left margin">
										<label>Material de Apoio</label><br>
										<div class="conteudoTexto">
											<?php echo '<a download="'.$o_atividade->getNomeMaterialApoio().'" href="views/abrir_arquivo.php?id='.$o_atividade->getIdAtividade().'" target="_blanck">'.$o_atividade->getNomeMaterialApoio().'</a>';
    		      			                 ?> 	
										</div>
									</div>	
						
									<div class="rightTop">
										<br><br><label>Tipo da Atividade</label><br><br>
											<?php if ($o_atividade->getTipoAtividade()==0) echo "Classe";
            						          else if ($o_atividade->getTipoAtividade()==1) echo "Extraclasse";
                            					else if ($o_atividade->getTipoAtividade()==2) echo "Complementar";
                       						?>
									</div>				
								</div>	
							<?php
                       	   }?>
        	   
						</div>				
						<div class="left margin">
							<br><label>Avaliação</label><br>
								<div class="conteudoTexto">
									<?php echo $o_praticadidatica->getAvaliacaoPratica()?> 
								</div>
						</div>	
						
						<div class="left margin">
							<br><br><label>Conclusão</label><br>
								<div class="conteudoTexto">
								<?php echo $o_praticadidatica->getConclusaoPratica()?>
							</div>
						</div>
						<div class="left margin">
							<label>Ações</label><br><br>
								<a href='?controle=Roteiro&acao=listarRoteiroPublico' class='bt_yellow'>Voltar</a>
						</div>
				
				</div>
</div>

</body>
</html>
