<?php 
$v_params = $this->getParams();
$v_logado = $v_params['v_logado'];
if(!isset($_SESSION)) 
    { 
        session_start(); 
    } 

 ?>
 
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Pratica Didatica | Login Usuário</title>

	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="views/images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="views/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="views/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="views/vendor/animate/animate.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="views/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="views/vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="views/vendor/select2/select2.min.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="views/vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="views/css/util.css">
	<link rel="stylesheet" type="text/css" href="views/css/main.css">
<!--===============================================================================================-->

</head>
<body>
	
	<div class="limiter">	
			<span class="banner">
					SACPD - Sistema de apoio ao compartilhamento de práticas didáticas
			</span>
			<br><br>
		
		<div class="container-login100">
			<div class="wrap-login100">		
				<form class="login100-form validate-form p-l-55 p-r-55 p-t-178" method="post">
					<span class="login100-form-title">
						Login
					</span>

					<div class="wrap-input100 validate-input m-b-16" data-validate="Please enter username">
						<input class="input100" type="text"  name="st_emailusuario" placeholder="E-mail do usuário">
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Please enter password">
						<input class="input100" type="password" name="st_senhausuario" class="form-control" placeholder="Senha do usuário">
						<span class="focus-input100"></span>
					</div>
					<br>

					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Entrar
						</button>
						
						<input type='hidden' name='controle' value='Usuario'>
						<input type='hidden' name='acao' value='loginUsuario'>
					</div>

					<div class="flex-col-c p-t-170 p-b-40">
						<span class="txt1 p-b-9">
							Não tem uma conta?
						</span>

						<a href='?controle=Usuario&acao=manterUsuario' class="txt3">
							Cadastre-se agora
						</a>
					</div>
				</form>
				<?php if ($v_logado=='N')
		          echo '<p>Usuário ou senha inválidos!';
	             ?>
			</div>
	</div>
	
	
<!--===============================================================================================-->
	<script src="vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/bootstrap/js/popper.js"></script>
	<script src="vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/daterangepicker/moment.min.js"></script>
	<script src="vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="js/main.js"></script>

</body>
</html>
