<?php
$v_params = $this->getParams();
$o_roteiro = $v_params['o_roteiro'];
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>
		Prática Didática - Manter Roteiro
	</title>
	<link rel="stylesheet" type="text/css" href="template/css/default.css" />
</head>
<body>
 <?php 


include("top.php");
include("menu.php")
?>
		<div class="agile_info">
			<div class="w3_info">
				<h2>Roteiro</h2>
				<form action="#" method="post">
				
							<div class="left margin">
								<label>Título</label>
									<div class="input-group">
										<input type="text" name='st_tituloroteiro' value='<?php echo $o_roteiro->getTituloRoteiro()?>'>
									</div>
							</div>
							
								<div class="rightTop">
											<label>Visibilidade</label>
									<br><br>
										<input type="radio" name="st_idvisibilidade" value="0"<?php echo ($o_roteiro->getIdVisibilidade() == 0) ? " checked" : null;?>> Roteiro Público<br>
					 					<input type="radio" name="st_idvisibilidade" value="1"<?php echo ($o_roteiro->getIdVisibilidade() == 1) ? " checked" : null;?>> Roteiro Privado<br> <br>
								</div>
							
								<div class="rightTop">
								<label>Ações</label><br><br>
									<div class="right">
										<a href='?controle=Roteiro&acao=listarRoteiro' class='bt_red'>Cancelar</a>
											<input type='hidden' name='controle' value='Roteiro'>
											<input type='hidden' name='acao' value='manterRoteiro'>
											<input type='hidden' name='in_idroteiro' value='<?php echo$o_roteiro->getIdRoteiro()?>'>
											<button type='submit' class='bt_green'>Salvar</button>
									</div>
							</div>
				
							<div class="left margin">
								<label>Objetivos Específicos</label>
									<div class="input-group">
										<textarea rows="70" cols="100" class="estilotextarea" name='st_objespecificoroteiro'><?php echo $o_roteiro->getObjEspecificoRoteiro()?></textarea>
									</div>
							</div>
			
							<div class="left margin">
								<label>Conteúdo Básico</label>
									<div class="input-group">
									<textarea rows="70" cols="100" class="estilotextarea" name='st_conteudobasicoroteiro'><?php echo $o_roteiro->getConteudoBasicoRoteiro()?></textarea>
							</div>
							
							<div class="left margin">
								<label>Palavras-chave</label>
									<div class="input-group">
										<input type="text"  name='st_palavrachaveroteiro' value='<?php echo $o_roteiro->getPalavraChaveRoteiro()?>'>
									</div>
							</div>
							
							<div class="left margin">						
							<label>Prática Didática</label><br><br><br>
								<a href='?controle=PraticaDidatica&acao=manterPraticaDidatica&in_idroteiro=<?php echo $o_roteiro->getIdRoteiro()?>' class="i2Style_green" style="color: #FFFFFF"> + Prática Didática </a>
							</div>
					</form>
	</div>
	</div>
</body>
</html>